// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.game.proto;

public final class ProtocolProto {
  private ProtocolProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *7位协议号 第一位1表示请求 2表示响应 3表示服务器通知 次三位表示模块id 后三位表示模块内协议号
   * </pre>
   *
   * Protobuf enum {@code protocol.ProtocolCmd}
   */
  public enum ProtocolCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 站位
     * </pre>
     *
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <pre>
     * 首包
     * </pre>
     *
     * <code>FIRST_CMD = 1001001;</code>
     */
    FIRST_CMD(1001001),
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>HEART_BEAT_CMD = 1002001;</code>
     */
    HEART_BEAT_CMD(1002001),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 站位
     * </pre>
     *
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <pre>
     * 首包
     * </pre>
     *
     * <code>FIRST_CMD = 1001001;</code>
     */
    public static final int FIRST_CMD_VALUE = 1001001;
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>HEART_BEAT_CMD = 1002001;</code>
     */
    public static final int HEART_BEAT_CMD_VALUE = 1002001;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtocolCmd valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ProtocolCmd forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1001001: return FIRST_CMD;
        case 1002001: return HEART_BEAT_CMD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtocolCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolCmd>() {
            public ProtocolCmd findValueByNumber(int number) {
              return ProtocolCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.proto.ProtocolProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtocolCmd[] VALUES = values();

    public static ProtocolCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtocolCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.ProtocolCmd)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\022\010protocol*>\n\013ProtocolCm" +
      "d\022\010\n\004NONE\020\000\022\017\n\tFIRST_CMD\020\251\214=\022\024\n\016HEART_BE" +
      "AT_CMD\020\221\224=B\037\n\016com.game.protoB\rProtocolPr" +
      "otob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
